export { Header } from "./header";
export { Navbar } from "./Navbar";
export { Hero } from "./hero";
export { Button } from "./button";
export { Features } from "./features";
export { MoreInformation } from "./more-information";
export { Testimonials } from "./testimonials";
export { Form } from "./form";
export { Footer } from "./footer/footer";   